---
- name: Deploy recipes app to minikube
  hosts: all
  tasks:
  # - name: Change directory
  #   command:
  #     chdir: /home/akash/Course/SPE/MajorProject
  #     cmd: ls -l
  # - name: show 
  #   shell: cat /kubernetes-config/recipe-backend-secret.yaml

  - name: apply secret
    shell: kubectl apply -f /home/akash/Course/SPE/MajorProject/kubernetes-config/recipe-backend-secret.yaml

  - name: apply backend
    shell: kubectl apply -f /home/akash/Course/SPE/MajorProject/kubernetes-config/recipe-backend.yaml

  - name: apply frontend
    shell: kubectl apply -f /home/akash/Course/SPE/MajorProject/kubernetes-config/recipe-frontend.yaml
