---
- name: Deploy recipes app to minikube
  hosts: all
  tasks:
  - name: Change directory
    command:
      chdir: /home/akash/Course/SPE/MajorProject
      cmd: ls -l
  - name: show 
    shell: ls -l

  - name: apply secret
    shell: kubectl apply -f /kubernetes-config/recipe-backend-secret.yaml

  - name: pull docker image
    shell: kubectl apply -f /kubernetes-config/recipe-backend.yaml

  - name: running container
    shell: kubectl apply -f /kubernetes-config/recipe-frontend.yaml
