---
- name: Deploy recipes app to minikube
  hosts: all
  remote_user: akash
  tasks:
  # - name: Clone repository
  #   git:
  #     repo: https://github.com/akashanand842/RecipeMedia-SPEMajor.git
  #     dest: /home/akash/RecipeMedia-SPEMajor
  #     version: sameeksha
  - name: folder
    shell: ls -l
    
  - name: pull docker image
    shell: kubectl apply -f ./../kubernetes-config/recipe-backend.yaml

  - name: running container
    shell: kubectl apply -f ./../kubernetes-config/recipe-frontend.yaml
