---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recipe-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  hostPath:
    path: /home/akash/majorproj-volume

