---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipe-volume-claim
spec:
  volumeName: recipe-volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
